# Generated by Django 5.1.7 on 2025-09-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Fotos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('rechazada', 'Rechazada'), ('eliminada', 'Eliminada')], default='pendiente', help_text='Estado actual de la asociación', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la asociación', null=True)),
                ('fecha_modificacion_estado', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha cuando fue aprobada la asociación', null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, help_text='Fecha cuando fue rechazada la asociación', null=True)),
                ('aprobada_por', models.CharField(blank=True, help_text='Quien aprobó la asociación', max_length=100, null=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador', null=True)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo (visible para la asociación)', null=True)),
                ('token_gestion', models.CharField(blank=True, help_text='Token único para gestión administrativa', max_length=64, unique=True)),
                ('token_aprobacion', models.CharField(blank=True, help_text='Token único para aprobación rápida', max_length=64, unique=True)),
                ('datos_completos_enviados', models.BooleanField(default=False, help_text='Si ya se enviaron los datos completos al admin')),
            ],
            options={
                'db_table': 'asociaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CreacionAnimales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_de_animal', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Fotos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=130)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adoptado', models.BooleanField(default=False)),
                ('color', models.CharField(default='No especificado', help_text='Color del animal (ej: marrón, negro, blanco, manchado, etc.)', max_length=100)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='myapp.registroasociacion')),
            ],
            options={
                'db_table': 'Animales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AnimalFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_ip', models.GenericIPAddressField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.creacionanimales')),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registroasociacion')),
            ],
            options={
                'unique_together': {('usuario_ip', 'animal')},
            },
        ),
    ]
