# Generated by Django 5.2 on 2025-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'asociaciones',
            },
        ),
    ]
