# Generated by Django 5.1.7 on 2025-09-24 20:06

import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionanimales',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del animal (máximo 5MB, formatos: JPG, PNG, GIF, WebP)', null=True, upload_to='animales/fotos/', validators=[myapp.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='video',
            field=models.FileField(blank=True, help_text='Video del animal (máximo 10MB, formatos: MP4, AVI, MOV, WebM)', null=True, upload_to='animales/videos/', validators=[myapp.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='registroasociacion',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la asociación (máximo 2MB, formatos: JPG, PNG)', null=True, upload_to='logos/', validators=[myapp.validators.validate_logo_file]),
        ),
    ]
