# Generated by Django 5.2 on 2025-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasociacion',
            name='password',
            field=models.CharField(default='contraseña1234', max_length=130),
            preserve_default=False,
        ),
    ]
