# Generated by Django 5.2 on 2025-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registroasociacion_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasociacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
