# Generated by Django 5.0.14 on 2025-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_creacionanimales_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionanimales',
            name='tamano',
            field=models.CharField(choices=[('Mini', 'Mini'), ('Pequeño', 'Pequeño'), ('Mediano-Pequeño', 'Mediano-Pequeño'), ('Mediano', 'Mediano'), ('Mediano-Grande', 'Mediano-Grande'), ('Grande', 'Grande')], default='Mediano', help_text='Tamaño del animal', max_length=20),
        ),
    ]
