# Generated by Django 5.2 on 2025-11-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creacionanimales_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionanimales',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la foto del animal en Backblaze B2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='video',
            field=models.URLField(blank=True, help_text='URL del video del animal en Backblaze B2', max_length=500, null=True),
        ),
    ]
