# Generated by Django 5.0.14 on 2025-11-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_creacionanimales_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(help_text='URL de la imagen del animal en Cloudinary', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización de la imagen')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es la imagen principal del animal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myapp.creacionanimales')),
            ],
            options={
                'verbose_name': 'Imagen de Animal',
                'verbose_name_plural': 'Imágenes de Animales',
                'db_table': 'imagenes_animales',
                'ordering': ['orden', '-es_principal', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(help_text='URL del video del animal en Cloudinary', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización del video')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del video', max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.creacionanimales')),
            ],
            options={
                'verbose_name': 'Video de Animal',
                'verbose_name_plural': 'Videos de Animales',
                'db_table': 'videos_animales',
                'ordering': ['orden', '-fecha_subida'],
            },
        ),
    ]
