# Generated by Django 5.2 on 2025-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_imagenanimal_videoanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasociacion',
            name='token_reset_expira',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del token de reset', null=True),
        ),
        migrations.AddField(
            model_name='registroasociacion',
            name='token_reset_password',
            field=models.CharField(blank=True, help_text='Token único para restablecer contraseña', max_length=64, null=True),
        ),
    ]
