# Generated by Django 5.2 on 2025-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_registroasociacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasociacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
