# Generated by Django 5.2 on 2025-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_registroasociacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreacionAnimales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_de_animal', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animales/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='animales/videos/')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=130)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Animales',
            },
        ),
    ]
