# Generated by Django 5.2 on 2025-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_creacionanimales'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionanimales',
            name='descripcion',
            field=models.CharField(default='mestizo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creacionanimales',
            name='raza',
            field=models.CharField(default='Mestizo', max_length=50),
            preserve_default=False,
        ),
    ]
