# Generated by Django 5.2 on 2025-06-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_creacionanimales_descripcion_creacionanimales_raza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creacionanimales',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='creacionanimales',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creacionanimales',
            name='asociacion',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='myapp.registroasociacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creacionanimales',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2010-12-28'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='tipo_de_animal',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=200),
        ),
    ]
