# Generated by Django 5.1.7 on 2025-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_creacionanimales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasociacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='tipo_de_animal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creacionanimales',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
