# Generated by Django 5.1.7 on 2025-09-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_registroasociacion_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_ip', models.GenericIPAddressField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.creacionanimales')),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registroasociacion')),
            ],
            options={
                'unique_together': {('usuario_ip', 'animal')},
            },
        ),
    ]
