# Generated by Django 5.1.7 on 2025-09-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_animalfavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionanimales',
            name='color',
            field=models.CharField(default='No especificado', help_text='Color del animal (ej: marrón, negro, blanco, manchado, etc.)', max_length=100),
        ),
    ]
